### PR TITLE
Remove cc_proto_library only when proto_library was removed

### LINKED ISSUE #76: bug: One run adds cc_proto_library targets, the next one removes them
Running gazelle with the proto,cc,go languages creates a proto_library and a cc_proto_library rules on the first run. A second run deletes the cc_proto_library target. Am I holding this wrong or is there an issue with the existing targets in the BUILD file?

Here is a repro PR where running //:gazelle deletes the cc_proto_library: https://github.com/satreix/everest/pull/1140

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #76  

When gazelle protobuf generation is disabled we should not remove the rules - these should be only removed if the upstream `language/proto` gazelle removes by adding them to `args.OtherEmpty`

### CODE REVIEW

File: language/cc/generate.go [hunk 1]
```diff
@@ -423,8 +423,9 @@ func (c *ccLanguage) findEmptyRules(args language.GenerateArgs, srcInfo ccSource
 			continue
 		}
 
-		if !slices.Contains(knownRuleKinds, resolveCCRuleKind(r.Kind(), args.Config)) {
+		if !slices.Contains(ccRuleDefs, resolveCCRuleKind(r.Kind(), args.Config)) {
 			// This rule is not managed by gazelle_cc
+			// proto_cc_library would be removed if related proto_library was removed (via args.OtherEmpty)
```
Comment (jayconrod) [inline language/cc/generate.go:428]:
```suggestion
			// cc_proto_library would be removed if related proto_library was removed (via args.OtherEmpty)
```

**Review by jayconrod — APPROVED** [review]
