### PR TITLE
Warn about unresolved includes

### LINKED ISSUE #96: Dependency resolution should warn if include cannot be resolved
Currently if we would not find a target defining a given include we silently ignore it. This however, can make analysing the outputs of generated rules more difficult. Instead we should at least print a warning to inform users that some of the `#include` directives were not resolved. 

- we should still ignore unresolved headers if these are a part of stdlib, e.g. a well known libc, libc++, posix or windows headers, we might need to create a builtin dictionary for these, alternativelly... 
- we can assume that all bracket `#include <path>` directives are using only system specific, builtin, headers (that might not be always the true due to `-isystem` flags) and can be ignored. I think going with this approach might be easier to maintain, especially because it might be harder to obtain full list of Windows SDK, or MacOS headers

We might want the logging to be configurable, let's say it can be done using dedicated directive `#gazelle:cc_unresolved_deps` taking following values 
- `ignore` - current behaviour, no logging, no errors 
- `warn` - warn about unresolved headers, probably a new default
- `error_fast` - print message about unresolved dependency and exit with error on first occurrence (useful for CI)
- `error` - same as `error_fast` but instead we'd like to continue resolving dependencies, so we can aggregate all the unresolved deps, and exit with error at the end of. For this one we might try to implement additional logic `language.LifecycleManager::AfterResolvingDeps` for our `ccLanguage` 

Probably a short message would be be good enough, e.g. `failed to resolve dependency for ${include} in ${ruleLabel.Pkg}:${ruleLabel:Name}`

### PR DESCRIPTION
**Pull request by mateusz-olczyk**
Defined a new _cc_unresolved_deps_ directive and implemented each mode.

Fixes #96

### CODE REVIEW

File: language/cc/resolve.go [hunk 1]
```diff
@@ -222,29 +247,32 @@ func compareLabels(l, r label.Label) int {
 	return strings.Compare(l.String(), r.String())
 }
 
-// Tries to resolve given importSpec using the following strategies:
+var (
+	errResolveErrorUnresolved              = errors.New("could not resolve the given importSpec")
+	errResolveErrorSelfImport              = errors.New("importSpec was resolved as a self-import")
```
Comment (jayconrod) [inline language/cc/resolve.go:252]: Same here: `library includes itself`. (I guess this shouldn't actually be reported though, right?)

File: language/cc/resolve.go [hunk 2]
```diff
@@ -222,29 +247,32 @@ func compareLabels(l, r label.Label) int {
...
+	errResolveErrorMissingModuleDependency = errors.New("importSpec was resolved to an external dependency unmentioned in MODULE.bazel")
```
Comment (jayconrod) [inline language/cc/resolve.go:253]: `header file found in external library not declared in MODULE.bazel`.

This should really say what the module is though.

**Review by jayconrod — COMMENTED** [review]
I have a few comments, but this looks good.

I regret that Gazelle doesn't have a better way for extensions to return errors. Ideally `Resolve` would just return an error, and this would all be handled by core Gazelle, rather than requiring each extension to do something like this. But there's no real fix outside of making an incompatible change to the common interfaces.

**Review by mateusz-olczyk — COMMENTED** [review]
I've replaced `ccLanguage.unresolvedIncludes` to the generic `ccLanguage.collectedErrors`. If you accept this, we could think later about refining the design of other errors. So not only unresolved includes, but also every other type of error could have its corresponding `cc_` config directive with possible values: `ignore`, `warning`, `error_fast`, `error`.

File: language/cc/resolve.go [hunk 3]
```diff
@@ -222,63 +249,64 @@ func compareLabels(l, r label.Label) int {
 	return strings.Compare(l.String(), r.String())
 }
 
-// Tries to resolve given importSpec using the following strategies:
+var (
+	errResolveErrorAmbiguousImport         = errors.New("multiple libraries provide the same header")
+	errResolveErrorMissingModuleDependency = errors.New("header file found in external library not declared in MODULE.bazel")
+	errResolveErrorSelfImport              = errors.New("library includes itself")
+	errResolveErrorUnresolved              = errors.New("could not find a library providing header")
```
[the remark this answers is not in the document]
Comment (mateusz-olczyk) [reply language/cc/resolve.go:256]: OK, but I'll leave `err` prefix due to https://staticcheck.dev/docs/checks#ST1012
