### PR TITLE
[parser] Handle function macro calls and improve #define directive representation

### LINKED ISSUE #78: CC parsers crashes on function macro calls
> hello @WojciechMazur thanks for this PoC, was testing your branch one some of my projects, i noticed that the parser has some glitches when it sees __has_include or __has_builtin like here in case of parsing this header https://github.com/fastfloat/fast_float/blob/b8085ba3634018ad6e5618cf87dd5a04a0e3f146/include/fast_float/bigint.h#L218
> 
> parser segfaults in parseExprPrecedence at line result, err = rule.infixParser(p, token, result)
> 
> ```
> [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100da8344]
> 
> goroutine 1 [running]:
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseExprPrecedence(0x14001229050, 0x0)
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:236 +0x204
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseExpr(...)
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:471
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseIfBranch(0x14001229050, {0x140004c0b70?, 0x140000478b8?}, 0x0)
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:542 +0x98
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseIfBlock(0x14001229050, {0x140004c0b70?, 0x140000479f8?})
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:566 +0x30
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseDirective(0x10118f578?, {0x140004c0b70?, 0x100e0cfe1?})
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:637 +0x1d8
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseDirectivesUntil(0x14001229050, 0x10118c9c0)
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:450 +0x1ec
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseIfBranch(0x14001229050, {0x140004c0b50?, 0x14000047c58?}, 0x0)
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:550 +0x264
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseIfBlock(0x14001229050, {0x140004c0b50?, 0x14000047d98?})
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:566 +0x30
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseDirective(0x10118f578?, {0x140004c0b50?, 0x100e0cfe1?})
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:637 +0x1d8
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.(*parser).parseDirectivesUntil(0x14001229050, 0x14000047f38)
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:450 +0x1ec
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.parse({0x10118f618, 0x14000122588})
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:426 +0x124
> github.com/EngFlow/gazelle_cc/language/internal/cc/parser.ParseSourceFile({0x14000f184c0, 0x32})
> 	external/gazelle_cc+/language/internal/cc/parser/parser.go:122 +0x10c
> github.com/EngFlow/gazelle_cc/language/cc.collectSourceInfos({0x14000191ad0, {0x140011b0420, 0x25}, {0x14000e31368, 0x7}, 0x14000389a40, {0x14000045360, 0x1, 0x1}, {0x140011bf688, ...}, ...})
> 	external/gazelle_cc+/language/cc/generate.go:325 +0x1c4
> github.com/EngFlow/gazelle_cc/language/cc.(*ccLanguage).GenerateRules(0x140002020c0, {0x14000191ad0, {0x140011b0420, 0x25}, {0x14000e31368, 0x7}, 0x14000389a40, {0x14000045360, 0x1, 0x1}, ...})
> 	external/gazelle_cc+/language/cc/generate.go:36 +0x64
> main.runFixUpdate.func2({{0x140011b0420, 0x25}, {0x14000e31368, 0x7}, 0x14000191ad0, 0x1, 0x14000389a40, {0x14000045360, 0x1, 0x1}, ...})
> 	external/gazelle+/cmd/gazelle/fix-update.go:355 +0x58c
> github.com/bazelbuild/bazel-gazelle/walk.(*walker).visit(0x1400021d9a0, 0x14000191ad0, {0x14000e31368, 0x7}, 0x1)
> 	external/gazelle+/walk/walk.go:503 +0x7fc
> github.com/bazelbuild/bazel-gazelle/walk.(*walker).visit(0x1400021d9a0, 0x140002b21a0, {0x0, 0x0}, 0x0)
> 	external/gazelle+/walk/walk.go:469 +0x5b0
> github.com/bazelbuild/bazel-gazelle/walk.Walk2(0x140002b21a0, {0x14000200120?, 0x100e0be45?, 0x4?}, {0x14000204860?, 0x3?, 0x14000200120?}, 0x6?, 0x1400017d6f8?)
> 	external/gazelle+/walk/walk.go:215 +0x4c
> main.runFixUpdate({0x1400002a1da, 0x1d}, 0x0, {0x14000144020, 0x3, 0x3})
> 	external/gazelle+/cmd/gazelle/fix-update.go:318 +0xa54
> main.run({0x1400002a1da?, 0x1d?}, {0x14000144010?, 0x4?, 0x4?})
> 	external/gazelle+/cmd/gazelle/main.go:95 +0x208
> main.main()
> 	external/gazelle+/cmd/gazelle/main.go:72 +0x104
> ```
> 
> i debugged it a bit by adding few log lines
> 
> ```
> ... Parsing file /Users/soanni/src/Cpp-Commons/include/fast_float.h ...
> +++#+++
> ***<nil>***
> +++#define+++
> ***#define FASTFLOAT_CONSTEXPR_FEATURE_DETECT_H ***
> +++#ifdef+++
> +++#if+++
> ---(---
> ^^^p=&{0x14001229020 {[] false}}, token=(, result=__has_include^^^
> panic: runtime error: invalid memory address or nil pointer dereference
> ```
> 
> here
> 
> ```
> // parseExprPrecedence implements Pratt parsing for expressions, handling C preprocessor conditionals.
> // minPrecedence controls operator binding (precedence climbing).
> func (p *parser) parseExprPrecedence(minPrecedence precedence) (Expr, error) {
> 	token, err := p.nextToken()
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	parsePrefix := getPrefixParseFn(token)
> 	result, err := parsePrefix(p, token)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	for {
> 		token, ok := p.tr.peek()
> 		fmt.Printf("---%s---\n", token)
> 		if !ok {
> 			return result, nil // end of input
> 		}
> 
> 		rule, exists := exprKeywordsPrecedence[token]
> 		if !exists || rule.precedence < minPrecedence {
> 			return result, nil // current operator binds less – stop and return
> 		}
> 		p.tr.mustConsume(token)
> 		fmt.Printf("^^^p=%v, token=%v, result=%v^^^", p, token, result)
> 		result, err = rule.infixParser(p, token, result)
> 		if err != nil {
> 			return nil, err
> 		}
> 	}
> }
> ```
>  

 _Originally posted by @soanni86 in [#73](https://github.com/EngFlow/gazelle_cc/issues/73#issuecomment-3068876297)_

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #78  
Parser is now able to handle function macro calls and represent them using `Expr.Apply` 
`DefineDirective` now contains explicit `Args` and `Body` variables instead of single `Tokens` to make evaluation possible in the future.

### CODE REVIEW

File: language/internal/cc/parser/directive.go [hunk 1]
```diff
@@ -71,7 +72,11 @@ func (d IncludeDirective) String() string {
 	return fmt.Sprintf("#include \"%s\"", d.Path)
 }
 func (d DefineDirective) String() string {
-	return fmt.Sprintf("#define %s %s", d.Name, strings.Join(d.Tokens, " "))
+	argsString := ""
+	if len(d.Args) >= 0 {
+		argsString = strings.Join(d.Args, ", ")
```
Comment (jayconrod) [inline language/internal/cc/parser/directive.go:77]: `argsString` should probably have the parenthesis here (so `"(" + strings.Join(d.Args, ", ") + ")"`). The format string below can then be `#define %s%s %s`. If there are no arguments, then no parenthesis needed.

**Review by jayconrod — APPROVED** [review]
